//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> IdWachPow { get; set; }
        public Nullable<int> IdWachMac { get; set; }
        public Nullable<int> IdWashing { get; set; }
        public Nullable<int> IdScore { get; set; }
        public Nullable<int> IdReport { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Drying Drying { get; set; }
        public virtual Report Report { get; set; }
        public virtual Score Score { get; set; }
        public virtual Washing Washing { get; set; }
    }
}
