//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Washing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Washing()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int IdWashing { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> IdDrying { get; set; }
        public Nullable<int> IdStaff { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdScore { get; set; }
        public Nullable<int> IdReport { get; set; }
        public Nullable<int> IdWashingMachines { get; set; }
        public Nullable<int> IdWashingPowser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual Drying Drying { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
        public virtual WashingMachines WashingMachines { get; set; }
        public virtual WashingPowder WashingPowder { get; set; }
    }
}
